[FIX] Update login.login_layout view priority to avoid view error
The next error appears when try to install the login module

ValueError: Element '<xpath expr="//t[@t-set='body_classname']">' cannot
be located in parent view

I reviewed and saas-15 and 11.0 version of web.login_layout view (the
inherited view) are exactly the same, So why does not find the element?

No syntax has been change between the versions. In version 11.0 I found
out that web.login_layout has a inherited view that does not exist in
saas-15: website.login_layout.

After making some tests changing login.login_layout priority to less than
16 which is the website.login_layout view priority the problem was
solved: Now will locate the elements of the original